#define BEARNUMBER 0
#include NAMEINCLUDE
#undef BEARNUMBER
 #define BEARNUMBER 1
 #include NAMEINCLUDE
 #undef BEARNUMBER
 #define BEARNUMBER 2
 #include NAMEINCLUDE
 #undef BEARNUMBER
 #define BEARNUMBER 3
 #include NAMEINCLUDE
#undef BEARNUMBER
 #define BEARNUMBER 4
 #include NAMEINCLUDE
 #undef BEARNUMBER
 #define BEARNUMBER 5
 #include NAMEINCLUDE
 #undef BEARNUMBER
 #define BEARNUMBER 6
 #include NAMEINCLUDE
 #undef BEARNUMBER
 #define BEARNUMBER 7
 #include NAMEINCLUDE
 #undef BEARNUMBER
 #define BEARNUMBER 8
 #include NAMEINCLUDE
 #undef BEARNUMBER
 #define BEARNUMBER 9
 #include NAMEINCLUDE
 #undef BEARNUMBER
 #define BEARNUMBER 10
 #include NAMEINCLUDE
 #undef BEARNUMBER
